(in-package :egl)


;; types from khrplatform.h
(defctype khronos_int8_t :int8)
(defctype khronos_uint8_t :uint8)
(defctype khronos_int16_t :int16)
(defctype khronos_uint16_t :uint16)
(defctype khronos_int32_t :int32)
(defctype khronos_uint32_t :uint32)
(defctype khronos_int64_t :int64)
(defctype khronos_uint64_t :uint64)


(eval-when (:compile-toplevel :load-toplevel :execute)
  ;; try to figure out a good size for intptr_t etc
  (cond
    ((= (foreign-type-size :pointer)
        (foreign-type-size :long))
     (defctype khronos_intptr_t :long)
     (defctype khronos_uintptr_t :unsigned-long)
     (defctype khronos_ssize_t :long)
     (defctype khronos_usize_t :unsigned-long))
    ((= (foreign-type-size :pointer)
         (foreign-type-size :long-long))
     (defctype khronos_intptr_t :long-long)
     (defctype khronos_uintptr_t :unsigned-long-long)
     (defctype khronos_ssize_t :long-long)
     (defctype khronos_usize_t :unsigned-long-long))
    (t (error "not sure how big intptr_t is on this platform"))))

(defctype khronos_float_t :float)
(defctype khronos_time_ns_t :uint64)

(defctype khronos_utime_nanoseconds_t :uint64)
(defctype khronos_stime_nanoseconds_t :int64)

(defctype EGLBoolean :uint)
(defctype EGLDisplay :pointer)
(defctype EGLConfig :pointer)
(defctype EGLSurface :pointer)
(defctype EGLContext :pointer)
(defctype EGLint :int32)

(defctype intptr_t khronos_intptr_t)


;; from eglplatfoprm.h
;;; depending on platform these are mostly pointers, intptr_t, or
;;; unsigned-long, so just storing them as uintptr_t to hide the
;;; pointers from lisp code. They also allow EGLEnum for 'default', so
;;; define a special type for that


(define-foreign-type enum-or-uintptr ()
  ()
  (:actual-type khronos_uintptr_t)
  (:simple-parser enum-or-uintptr))

(defmethod translate-to-foreign (value (type enum-or-uintptr))
  (if (keywordp value)
      (foreign-enum-value 'eglenum value)
      value))

(defmethod expand-to-foreign (value (type enum-or-uintptr))
  (cond
    ((and (constantp value) (keywordp value))
     (foreign-enum-value 'eglenum value))
    ((numberp value)
     value)
    (t
     (alexandria:once-only (value)
       `(if (keywordp ,value)
            (foreign-enum-value 'eglenum ,value)
            ,value)))))

(defctype EGLNativeDisplayType enum-or-uintptr) ;; int on ios?
(defctype EGLNativePixmapType enum-or-uintptr)
(defctype EGLNativeWindowType enum-or-uintptr)

(defctype NativeDisplayType EGLNativeDisplayType )
(defctype NativePixmapType EGLNativePixmapType)
(defctype NativeWindowType EGLNativeWindowType)



;;; types extracted/generated from egl.xml
(defcstruct AHardwareBuffer)

(defctype EGLBoolean :unsigned-int)
(defctype EGLenum :unsigned-int)
(defctype EGLAttribKHR intptr_t)
(defctype EGLAttrib intptr_t)
(defctype EGLClientBuffer (:pointer :void))
(defctype EGLConfig (:pointer :void))
(defctype EGLContext (:pointer :void))
(defctype EGLDeviceEXT (:pointer :void))
(defctype EGLDisplay (:pointer :void))
(defctype EGLImage (:pointer :void))
(defctype EGLImageKHR (:pointer :void))
(defctype EGLLabelKHR (:pointer :void))
(defctype EGLObjectKHR (:pointer :void))
(defctype EGLOutputLayerEXT (:pointer :void))
(defctype EGLOutputPortEXT (:pointer :void))
(defctype EGLStreamKHR (:pointer :void))
(defctype EGLSurface (:pointer :void))
(defctype EGLSync (:pointer :void))
(defctype EGLSyncKHR (:pointer :void))
(defctype EGLSyncNV (:pointer :void))
(defctype __eglMustCastToProperFunctionPointerType
    (:pointer
     #| void (*__eglMustCastToProperFunctionPointerType)(void) |#))

(defctype EGLTimeKHR khronos_utime_nanoseconds_t)
(defctype EGLTime khronos_utime_nanoseconds_t)
(defctype EGLTimeNV khronos_utime_nanoseconds_t)
(defctype EGLuint64NV khronos_utime_nanoseconds_t)
(defctype EGLuint64KHR khronos_uint64_t)
(defctype EGLnsecsANDROID khronos_stime_nanoseconds_t)
(defctype EGLNativeFileDescriptorKHR :int)
(defctype EGLsizeiANDROID khronos_ssize_t)
(defctype EGLSetBlobFuncANDROID
    (:pointer
     #| void (*EGLSetBlobFuncANDROID) (const void *key, EGLsizeiANDROID keySize, const void *value, EGLsizeiANDROID valueSize) |#))

(defctype EGLGetBlobFuncANDROID
    (:pointer
     #| EGLsizeiANDROID (*EGLGetBlobFuncANDROID) (const void *key, EGLsizeiANDROID keySize, void *value, EGLsizeiANDROID valueSize) |#))

(defcstruct EGLClientPixmapHI
  (pData (:pointer :void))
  (iWidth EGLint)
  (iHeight EGLint)
  (iStride EGLint))

(defctype EGLDEBUGPROCKHR
    (:pointer
     #| void ( *EGLDEBUGPROCKHR)(EGLenum error,const char *command,EGLint messageType,EGLLabelKHR threadLabel,EGLLabelKHR objectLabel,const char* message) |#))


(defbitfield EGLSurfaceTypeMask
  (:pbuffer-bit #x1)
  (:pixmap-bit #x2)
  (:window-bit #x4)
  (:pbuffer-image-bit-tao #x8)
  (:pbuffer-palette-image-bit-tao #x10)
  (:vg-colorspace-linear-bit #x20)
  (:vg-colorspace-linear-bit-khr #x20)
  (:vg-alpha-format-pre-bit #x40)
  (:vg-alpha-format-pre-bit-khr #x40)
  (:lock-surface-bit-khr #x80)
  (:optimal-format-bit-khr #x100)
  (:multisample-resolve-box-bit #x200)
  (:swap-behavior-preserved-bit #x400)
  (:stream-bit-khr #x800)
  (:mutable-render-buffer-bit-khr #x1000))

(defbitfield EGLRenderableTypeMask
  (:opengl-es-bit #x1)
  (:openvg-bit #x2)
  (:opengl-es2-bit #x4)
  (:opengl-bit #x8)
  (:interop-bit-khr #x10)
  (:openmax-il-bit-khr #x20)
  (:opengl-es3-bit #x40)
  (:opengl-es3-bit-khr #x40))

(defbitfield EGLLockUsageHintKHRMask
  (:read-surface-bit-khr #x1)
  (:write-surface-bit-khr #x2))

(defbitfield EGLNativeBufferUsageFlags
  (:native-buffer-usage-protected-bit-android #x1)
  (:native-buffer-usage-renderbuffer-bit-android #x2)
  (:native-buffer-usage-texture-bit-android #x4))

(defbitfield EGLSyncFlagsKHR
  (:sync-flush-commands-bit #x1)
  (:sync-flush-commands-bit-khr #x1)
  (:sync-flush-commands-bit-nv #x1))

(defbitfield EGLDRMBufferUseMESAMask
  (:drm-buffer-use-scanout-mesa #x1)
  (:drm-buffer-use-share-mesa #x2)
  (:drm-buffer-use-cursor-mesa #x4))

(defbitfield EGLContextFlagMask
  (:context-opengl-debug-bit-khr #x1)
  (:context-opengl-forward-compatible-bit-khr #x2)
  (:context-opengl-robust-access-bit-khr #x4))

(defbitfield EGLContextProfileMask
  (:context-opengl-core-profile-bit #x1)
  (:context-opengl-core-profile-bit-khr #x1)
  (:context-opengl-compatibility-profile-bit #x2)
  (:context-opengl-compatibility-profile-bit-khr #x2))

(defcenum (eglenum EGLint)
  (:timestamp-pending-android #x-2)
  (:timestamp-invalid-android #x-1)
  (:dont-care #x-1)
  (:unknown #x-1)
  (:no-native-fence-fd-android #x-1)
  (:no-file-descriptor-khr #x-1)
  (:depth-encoding-none-nv #x0)
  (:no-context #x0)
  (:no-device-ext #x0)
  (:no-display #x0)
  (:no-image #x0)
  (:no-image-khr #x0)
  (:default-display #x0)
  (:no-output-layer-ext #x0)
  (:no-output-port-ext #x0)
  (:no-stream-khr #x0)
  (:no-surface #x0)
  (:no-sync #x0)
  (:no-sync-khr #x0)
  (:no-sync-nv #x0)
  (:no-config-khr #x0)
  (:false #x0)
  (:context-release-behavior-none-khr #x0)
  (:true #x1)
  (:context-release-behavior-khr #x2097)
  (:context-release-behavior-flush-khr #x2098)
  (:display-scaling #x2710)
  (:success #x3000)
  (:not-initialized #x3001)
  (:bad-access #x3002)
  (:bad-alloc #x3003)
  (:bad-attribute #x3004)
  (:bad-config #x3005)
  (:bad-context #x3006)
  (:bad-current-surface #x3007)
  (:bad-display #x3008)
  (:bad-match #x3009)
  (:bad-native-pixmap #x300A)
  (:bad-native-window #x300B)
  (:bad-parameter #x300C)
  (:bad-surface #x300D)
  (:context-lost #x300E)
  (:buffer-size #x3020)
  (:alpha-size #x3021)
  (:blue-size #x3022)
  (:green-size #x3023)
  (:red-size #x3024)
  (:depth-size #x3025)
  (:stencil-size #x3026)
  (:config-caveat #x3027)
  (:config-id #x3028)
  (:level #x3029)
  (:max-pbuffer-height #x302A)
  (:max-pbuffer-pixels #x302B)
  (:max-pbuffer-width #x302C)
  (:native-renderable #x302D)
  (:native-visual-id #x302E)
  (:native-visual-type #x302F)
  (:samples #x3031)
  (:sample-buffers #x3032)
  (:surface-type #x3033)
  (:transparent-type #x3034)
  (:transparent-blue-value #x3035)
  (:transparent-green-value #x3036)
  (:transparent-red-value #x3037)
  (:none #x3038)
  (:bind-to-texture-rgb #x3039)
  (:bind-to-texture-rgba #x303A)
  (:min-swap-interval #x303B)
  (:max-swap-interval #x303C)
  (:luminance-size #x303D)
  (:alpha-mask-size #x303E)
  (:color-buffer-type #x303F)
  (:renderable-type #x3040)
  (:match-native-pixmap #x3041)
  (:conformant #x3042)
  (:conformant-khr #x3042)
  (:match-format-khr #x3043)
  (:slow-config #x3050)
  (:non-conformant-config #x3051)
  (:transparent-rgb #x3052)
  (:vendor #x3053)
  (:version #x3054)
  (:extensions #x3055)
  (:height #x3056)
  (:width #x3057)
  (:largest-pbuffer #x3058)
  (:draw #x3059)
  (:read #x305A)
  (:core-native-engine #x305B)
  (:no-texture #x305C)
  (:texture-rgb #x305D)
  (:texture-rgba #x305E)
  (:texture-2d #x305F)
  (:y-inverted-nok #x307F)
  (:texture-format #x3080)
  (:texture-target #x3081)
  (:mipmap-texture #x3082)
  (:mipmap-level #x3083)
  (:back-buffer #x3084)
  (:single-buffer #x3085)
  (:render-buffer #x3086)
  (:colorspace #x3087)
  (:vg-colorspace #x3087)
  (:alpha-format #x3088)
  (:vg-alpha-format #x3088)
  (:colorspace-srgb #x3089)
  (:gl-colorspace-srgb #x3089)
  (:gl-colorspace-srgb-khr #x3089)
  (:vg-colorspace-srgb #x3089)
  (:colorspace-linear #x308A)
  (:gl-colorspace-linear #x308A)
  (:gl-colorspace-linear-khr #x308A)
  (:vg-colorspace-linear #x308A)
  (:alpha-format-nonpre #x308B)
  (:vg-alpha-format-nonpre #x308B)
  (:alpha-format-pre #x308C)
  (:vg-alpha-format-pre #x308C)
  (:client-apis #x308D)
  (:rgb-buffer #x308E)
  (:luminance-buffer #x308F)
  (:horizontal-resolution #x3090)
  (:vertical-resolution #x3091)
  (:pixel-aspect-ratio #x3092)
  (:swap-behavior #x3093)
  (:buffer-preserved #x3094)
  (:buffer-destroyed #x3095)
  (:openvg-image #x3096)
  (:context-client-type #x3097)
  (:context-client-version #x3098)
  (:context-major-version #x3098)
  (:context-major-version-khr #x3098)
  (:multisample-resolve #x3099)
  (:multisample-resolve-default #x309A)
  (:multisample-resolve-box #x309B)
  (:cl-event-handle #x309C)
  (:cl-event-handle-khr #x309C)
  (:gl-colorspace #x309D)
  (:gl-colorspace-khr #x309D)
  (:opengl-es-api #x30A0)
  (:openvg-api #x30A1)
  (:opengl-api #x30A2)
  (:native-pixmap-khr #x30B0)
  (:gl-texture-2d #x30B1)
  (:gl-texture-2d-khr #x30B1)
  (:gl-texture-3d #x30B2)
  (:gl-texture-3d-khr #x30B2)
  (:gl-texture-cube-map-positive-x #x30B3)
  (:gl-texture-cube-map-positive-x-khr #x30B3)
  (:gl-texture-cube-map-negative-x #x30B4)
  (:gl-texture-cube-map-negative-x-khr #x30B4)
  (:gl-texture-cube-map-positive-y #x30B5)
  (:gl-texture-cube-map-positive-y-khr #x30B5)
  (:gl-texture-cube-map-negative-y #x30B6)
  (:gl-texture-cube-map-negative-y-khr #x30B6)
  (:gl-texture-cube-map-positive-z #x30B7)
  (:gl-texture-cube-map-positive-z-khr #x30B7)
  (:gl-texture-cube-map-negative-z #x30B8)
  (:gl-texture-cube-map-negative-z-khr #x30B8)
  (:gl-renderbuffer #x30B9)
  (:gl-renderbuffer-khr #x30B9)
  (:vg-parent-image-khr #x30BA)
  (:gl-texture-level #x30BC)
  (:gl-texture-level-khr #x30BC)
  (:gl-texture-zoffset #x30BD)
  (:gl-texture-zoffset-khr #x30BD)
  (:post-sub-buffer-supported-nv #x30BE)
  (:context-opengl-robust-access-ext #x30BF)
  (:format-rgb-565-exact-khr #x30C0)
  (:format-rgb-565-khr #x30C1)
  (:format-rgba-8888-exact-khr #x30C2)
  (:format-rgba-8888-khr #x30C3)
  (:map-preserve-pixels-khr #x30C4)
  (:lock-usage-hint-khr #x30C5)
  (:bitmap-pointer-khr #x30C6)
  (:bitmap-pitch-khr #x30C7)
  (:bitmap-origin-khr #x30C8)
  (:bitmap-pixel-red-offset-khr #x30C9)
  (:bitmap-pixel-green-offset-khr #x30CA)
  (:bitmap-pixel-blue-offset-khr #x30CB)
  (:bitmap-pixel-alpha-offset-khr #x30CC)
  (:bitmap-pixel-luminance-offset-khr #x30CD)
  (:lower-left-khr #x30CE)
  (:upper-left-khr #x30CF)
  (:image-preserved #x30D2)
  (:image-preserved-khr #x30D2)
  (:shared-image-nok #x30DA)
  (:coverage-buffers-nv #x30E0)
  (:coverage-samples-nv #x30E1)
  (:depth-encoding-nv #x30E2)
  (:depth-encoding-nonlinear-nv #x30E3)
  (:sync-prior-commands-complete-nv #x30E6)
  (:sync-status-nv #x30E7)
  (:signaled-nv #x30E8)
  (:unsignaled-nv #x30E9)
  (:already-signaled-nv #x30EA)
  (:timeout-expired-nv #x30EB)
  (:condition-satisfied-nv #x30EC)
  (:sync-type-nv #x30ED)
  (:sync-condition-nv #x30EE)
  (:sync-fence-nv #x30EF)
  (:sync-prior-commands-complete #x30F0)
  (:sync-prior-commands-complete-khr #x30F0)
  (:sync-status #x30F1)
  (:sync-status-khr #x30F1)
  (:signaled #x30F2)
  (:signaled-khr #x30F2)
  (:unsignaled #x30F3)
  (:unsignaled-khr #x30F3)
  (:timeout-expired #x30F5)
  (:timeout-expired-khr #x30F5)
  (:condition-satisfied #x30F6)
  (:condition-satisfied-khr #x30F6)
  (:sync-type #x30F7)
  (:sync-type-khr #x30F7)
  (:sync-condition #x30F8)
  (:sync-condition-khr #x30F8)
  (:sync-fence #x30F9)
  (:sync-fence-khr #x30F9)
  (:sync-reusable-khr #x30FA)
  (:context-minor-version #x30FB)
  (:context-minor-version-khr #x30FB)
  (:context-flags-khr #x30FC)
  (:context-opengl-profile-mask #x30FD)
  (:context-opengl-profile-mask-khr #x30FD)
  (:sync-cl-event #x30FE)
  (:sync-cl-event-khr #x30FE)
  (:sync-cl-event-complete #x30FF)
  (:sync-cl-event-complete-khr #x30FF)
  (:context-priority-level-img #x3100)
  (:context-priority-high-img #x3101)
  (:context-priority-medium-img #x3102)
  (:context-priority-low-img #x3103)
  (:native-buffer-multiplane-separate-img #x3105)
  (:native-buffer-plane-offset-img #x3106)
  (:bitmap-pixel-size-khr #x3110)
  (:coverage-sample-resolve-nv #x3131)
  (:coverage-sample-resolve-default-nv #x3132)
  (:coverage-sample-resolve-none-nv #x3133)
  (:multiview-view-count-ext #x3134)
  (:auto-stereo-nv #x3136)
  (:context-opengl-reset-notification-strategy-ext #x3138)
  (:buffer-age-khr #x313D)
  (:buffer-age-ext #x313D)
  (:platform-device-ext #x313F)
  (:native-buffer-android #x3140)
  (:platform-android-khr #x3141)
  (:recordable-android #x3142)
  (:native-buffer-usage-android #x3143)
  (:sync-native-fence-android #x3144)
  (:sync-native-fence-fd-android #x3145)
  (:sync-native-fence-signaled-android #x3146)
  (:framebuffer-target-android #x3147)
  (:front-buffer-auto-refresh-android #x314C)
  (:gl-colorspace-default-ext #x314D)
  (:context-opengl-debug #x31B0)
  (:context-opengl-forward-compatible #x31B1)
  (:context-opengl-robust-access #x31B2)
  (:context-opengl-no-error-khr #x31B3)
  (:context-opengl-reset-notification-strategy-khr #x31BD)
  (:context-opengl-reset-notification-strategy #x31BD)
  (:no-reset-notification #x31BE)
  (:no-reset-notification-khr #x31BE)
  (:no-reset-notification-ext #x31BE)
  (:lose-context-on-reset #x31BF)
  (:lose-context-on-reset-khr #x31BF)
  (:lose-context-on-reset-ext #x31BF)
  (:drm-buffer-format-mesa #x31D0)
  (:drm-buffer-use-mesa #x31D1)
  (:drm-buffer-format-argb32-mesa #x31D2)
  (:drm-buffer-mesa #x31D3)
  (:drm-buffer-stride-mesa #x31D4)
  (:platform-x11-khr #x31D5)
  (:platform-x11-ext #x31D5)
  (:platform-x11-screen-khr #x31D6)
  (:platform-x11-screen-ext #x31D6)
  (:platform-gbm-khr #x31D7)
  (:platform-gbm-mesa #x31D7)
  (:platform-wayland-khr #x31D8)
  (:platform-wayland-ext #x31D8)
  (:platform-surfaceless-mesa #x31DD)
  (:stream-fifo-length-khr #x31FC)
  (:stream-time-now-khr #x31FD)
  (:stream-time-consumer-khr #x31FE)
  (:stream-time-producer-khr #x31FF)
  (:d3d-texture-2d-share-handle-angle #x3200)
  (:fixed-size-angle #x3201)
  (:consumer-latency-usec-khr #x3210)
  (:producer-frame-khr #x3212)
  (:consumer-frame-khr #x3213)
  (:stream-state-khr #x3214)
  (:stream-state-created-khr #x3215)
  (:stream-state-connecting-khr #x3216)
  (:stream-state-empty-khr #x3217)
  (:stream-state-new-frame-available-khr #x3218)
  (:stream-state-old-frame-available-khr #x3219)
  (:stream-state-disconnected-khr #x321A)
  (:bad-stream-khr #x321B)
  (:bad-state-khr #x321C)
  (:buffer-count-nv #x321D)
  (:consumer-acquire-timeout-usec-khr #x321E)
  (:sync-new-frame-nv #x321F)
  (:bad-device-ext #x322B)
  (:device-ext #x322C)
  (:bad-output-layer-ext #x322D)
  (:bad-output-port-ext #x322E)
  (:swap-interval-ext #x322F)
  (:drm-device-file-ext #x3233)
  (:drm-crtc-ext #x3234)
  (:drm-plane-ext #x3235)
  (:drm-connector-ext #x3236)
  (:openwf-device-id-ext #x3237)
  (:openwf-pipeline-id-ext #x3238)
  (:openwf-port-id-ext #x3239)
  (:cuda-device-nv #x323A)
  (:cuda-event-handle-nv #x323B)
  (:sync-cuda-event-nv #x323C)
  (:sync-cuda-event-complete-nv #x323D)
  (:stream-cross-partition-nv #x323F)
  (:stream-state-initializing-nv #x3240)
  (:stream-type-nv #x3241)
  (:stream-protocol-nv #x3242)
  (:stream-endpoint-nv #x3243)
  (:stream-local-nv #x3244)
  (:stream-cross-process-nv #x3245)
  (:stream-protocol-fd-nv #x3246)
  (:stream-producer-nv #x3247)
  (:stream-consumer-nv #x3248)
  (:stream-protocol-socket-nv #x324B)
  (:socket-handle-nv #x324C)
  (:socket-type-nv #x324D)
  (:socket-type-unix-nv #x324E)
  (:socket-type-inet-nv #x324F)
  (:max-stream-metadata-blocks-nv #x3250)
  (:max-stream-metadata-block-size-nv #x3251)
  (:max-stream-metadata-total-size-nv #x3252)
  (:producer-metadata-nv #x3253)
  (:consumer-metadata-nv #x3254)
  (:metadata0-size-nv #x3255)
  (:metadata1-size-nv #x3256)
  (:metadata2-size-nv #x3257)
  (:metadata3-size-nv #x3258)
  (:metadata0-type-nv #x3259)
  (:metadata1-type-nv #x325A)
  (:metadata2-type-nv #x325B)
  (:metadata3-type-nv #x325C)
  (:linux-dma-buf-ext #x3270)
  (:linux-drm-fourcc-ext #x3271)
  (:dma-buf-plane0-fd-ext #x3272)
  (:dma-buf-plane0-offset-ext #x3273)
  (:dma-buf-plane0-pitch-ext #x3274)
  (:dma-buf-plane1-fd-ext #x3275)
  (:dma-buf-plane1-offset-ext #x3276)
  (:dma-buf-plane1-pitch-ext #x3277)
  (:dma-buf-plane2-fd-ext #x3278)
  (:dma-buf-plane2-offset-ext #x3279)
  (:dma-buf-plane2-pitch-ext #x327A)
  (:yuv-color-space-hint-ext #x327B)
  (:sample-range-hint-ext #x327C)
  (:yuv-chroma-horizontal-siting-hint-ext #x327D)
  (:yuv-chroma-vertical-siting-hint-ext #x327E)
  (:itu-rec601-ext #x327F)
  (:itu-rec709-ext #x3280)
  (:itu-rec2020-ext #x3281)
  (:yuv-full-range-ext #x3282)
  (:yuv-narrow-range-ext #x3283)
  (:yuv-chroma-siting-0-ext #x3284)
  (:yuv-chroma-siting-0-5-ext #x3285)
  (:discard-samples-arm #x3286)
  (:sync-prior-commands-implicit-external-arm #x328A)
  (:native-buffer-tizen #x32A0)
  (:native-surface-tizen #x32A1)
  (:protected-content-ext #x32C0)
  (:yuv-buffer-ext #x3300)
  (:yuv-order-ext #x3301)
  (:yuv-order-yuv-ext #x3302)
  (:yuv-order-yvu-ext #x3303)
  (:yuv-order-yuyv-ext #x3304)
  (:yuv-order-uyvy-ext #x3305)
  (:yuv-order-yvyu-ext #x3306)
  (:yuv-order-vyuy-ext #x3307)
  (:yuv-order-ayuv-ext #x3308)
  (:yuv-csc-standard-ext #x330A)
  (:yuv-csc-standard-601-ext #x330B)
  (:yuv-csc-standard-709-ext #x330C)
  (:yuv-csc-standard-2020-ext #x330D)
  (:yuv-number-of-planes-ext #x3311)
  (:yuv-subsample-ext #x3312)
  (:yuv-subsample-4-2-0-ext #x3313)
  (:yuv-subsample-4-2-2-ext #x3314)
  (:yuv-subsample-4-4-4-ext #x3315)
  (:yuv-depth-range-ext #x3317)
  (:yuv-depth-range-limited-ext #x3318)
  (:yuv-depth-range-full-ext #x3319)
  (:yuv-plane-bpp-ext #x331A)
  (:yuv-plane-bpp-0-ext #x331B)
  (:yuv-plane-bpp-8-ext #x331C)
  (:yuv-plane-bpp-10-ext #x331D)
  (:pending-metadata-nv #x3328)
  (:pending-frame-nv #x3329)
  (:stream-time-pending-nv #x332A)
  (:yuv-plane0-texture-unit-nv #x332C)
  (:yuv-plane1-texture-unit-nv #x332D)
  (:yuv-plane2-texture-unit-nv #x332E)
  (:support-reset-nv #x3334)
  (:support-reuse-nv #x3335)
  (:stream-fifo-synchronous-nv #x3336)
  (:producer-max-frame-hint-nv #x3337)
  (:consumer-max-frame-hint-nv #x3338)
  (:color-component-type-ext #x3339)
  (:color-component-type-fixed-ext #x333A)
  (:color-component-type-float-ext #x333B)
  (:drm-master-fd-ext #x333C)
  (:gl-colorspace-bt2020-linear-ext #x333F)
  (:gl-colorspace-bt2020-pq-ext #x3340)
  (:smpte2086-display-primary-rx-ext #x3341)
  (:smpte2086-display-primary-ry-ext #x3342)
  (:smpte2086-display-primary-gx-ext #x3343)
  (:smpte2086-display-primary-gy-ext #x3344)
  (:smpte2086-display-primary-bx-ext #x3345)
  (:smpte2086-display-primary-by-ext #x3346)
  (:smpte2086-white-point-x-ext #x3347)
  (:smpte2086-white-point-y-ext #x3348)
  (:smpte2086-max-luminance-ext #x3349)
  (:smpte2086-min-luminance-ext #x334A)
  (:generate-reset-on-video-memory-purge-nv #x334C)
  (:stream-cross-object-nv #x334D)
  (:stream-cross-display-nv #x334E)
  (:stream-cross-system-nv #x334F)
  (:gl-colorspace-scrgb-linear-ext #x3350)
  (:gl-colorspace-scrgb-ext #x3351)
  (:track-references-khr #x3352)
  (:context-priority-realtime-nv #x3357)
  (:cta861-3-max-content-light-level-ext #x3360)
  (:cta861-3-max-frame-average-level-ext #x3361)
  (:gl-colorspace-display-p3-linear-ext #x3362)
  (:gl-colorspace-display-p3-ext #x3363)
  (:sync-client-ext #x3364)
  (:sync-client-signal-ext #x3365)
  (:d3d9-device-angle #x33A0)
  (:d3d11-device-angle #x33A1)
  (:object-thread-khr #x33B0)
  (:object-display-khr #x33B1)
  (:object-context-khr #x33B2)
  (:object-surface-khr #x33B3)
  (:object-image-khr #x33B4)
  (:object-sync-khr #x33B5)
  (:object-stream-khr #x33B6)
  (:debug-callback-khr #x33B8)
  (:debug-msg-critical-khr #x33B9)
  (:debug-msg-error-khr #x33BA)
  (:debug-msg-warn-khr #x33BB)
  (:debug-msg-info-khr #x33BC)
  (:timestamps-android #x3430)
  (:composite-deadline-android #x3431)
  (:composite-interval-android #x3432)
  (:composite-to-present-latency-android #x3433)
  (:requested-present-time-android #x3434)
  (:rendering-complete-time-android #x3435)
  (:composition-latch-time-android #x3436)
  (:first-composition-start-time-android #x3437)
  (:last-composition-start-time-android #x3438)
  (:first-composition-gpu-finished-time-android #x3439)
  (:display-present-time-android #x343A)
  (:dequeue-ready-time-android #x343B)
  (:reads-done-time-android #x343C)
  (:dma-buf-plane3-fd-ext #x3440)
  (:dma-buf-plane3-offset-ext #x3441)
  (:dma-buf-plane3-pitch-ext #x3442)
  (:dma-buf-plane0-modifier-lo-ext #x3443)
  (:dma-buf-plane0-modifier-hi-ext #x3444)
  (:dma-buf-plane1-modifier-lo-ext #x3445)
  (:dma-buf-plane1-modifier-hi-ext #x3446)
  (:dma-buf-plane2-modifier-lo-ext #x3447)
  (:dma-buf-plane2-modifier-hi-ext #x3448)
  (:dma-buf-plane3-modifier-lo-ext #x3449)
  (:dma-buf-plane3-modifier-hi-ext #x344A)
  (:primary-compositor-context-ext #x3460)
  (:external-ref-id-ext #x3461)
  (:compositor-drop-newest-frame-ext #x3462)
  (:compositor-keep-newest-frame-ext #x3463)
  (:front-buffer-ext #x3464)
  (:import-sync-type-ext #x3470)
  (:import-implicit-sync-ext #x3471)
  (:import-explicit-sync-ext #x3472)
  (:color-format-hi #x8F70)
  (:color-rgb-hi #x8F71)
  (:color-rgba-hi #x8F72)
  (:color-argb-hi #x8F73)
  (:client-pixmap-pointer-hi #x8F74)
  (:metadata-scaling-ext #xC350)
  (:forever #xFFFFFFFFFFFFFFFF)
  (:forever-khr #xFFFFFFFFFFFFFFFF)
  (:forever-nv #xFFFFFFFFFFFFFFFF))
